workflow:
  - request: Access httpbin
    method: GET
    url: https://httpbin.org/get
    retry_period: 2
    assertion:
      name: Expect code 200
      expectedcode: 200
      onfailure: retry
  - request: Access google
    method: GET
    url: https://google.com
    retry_period: 2
    assertion:
      name: Expect code 200
      expectedcode: 200
      onfailure: retry
  - request: Post a message to httpbin
    method: POST
    url: https://httpbin.org/post
    body: '{"message": "hello world"}'
    retry_period: 2
    assertion:
      name: Expect code 200
      expectedcode: 200
      onfailure: retry